### ISSUE TITLE
Prototype a report card for a state

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVIDMINDER#11]
Make a snapshot of where the state is.  could be a star plot with sectors for the various type of factors.

**Comment by Darokrithia** [comment]
@bennek2 Just to clarify: by "Make a snapshot of where the state is." do you mean how far into the lifecycle of the infection the state is? Or just generally how the state is doing?

**Comment by Darokrithia** [comment]
I will work on this the notebooks repo https://github.com/TheRensselaerIDEA/COVID-Notebooks/

**Comment by Darokrithia** [comment]
For future notice this issue will specifically be worked on here https://github.com/TheRensselaerIDEA/COVIDMINDER/issues/282

**Comment by Darokrithia** [comment]
This is the new location of this issue https://github.com/TheRensselaerIDEA/COVID-Notebooks/issues/31

**Comment by josefigueroa168** [comment]
Done
