### ISSUE TITLE
Reconcile data downloaders

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/COVIDMINDER#168]
Currently we must run several scripts each morning IN A PARTICULAR ORDER to grad the updates from various sources. In addition --- actually, prior to running the scripts! --- the NYS daily fatalities data must be manually scraped and updated.

**Comment by josefigueroa168** [comment]
While the particular order is still somewhat relevant, it has been largely mediated. Also, we are no longer manually scraping.
