### ISSUE TITLE
Create README for data_downloaders

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/COVIDMINDER#169]
@olyerickson needs to create a README to explain what the heck is going on with the downloading...

**Comment by olyerickson** [comment]
PARTIALLY complete; we have a README for daily downloading, but not much detail *inside* the downloaders...

**Comment by josefigueroa168** [comment]
Scripts now work as one (source_downloaders) with no manual component. Some redundant downloads are happening I think but mostly harmless.
