### ISSUE TITLE
Create map image exporter

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/COVIDMINDER#170]
There are programmatic ways to export leaflet maps; one approach is described here:

https://stackoverflow.com/questions/31336898/how-to-save-leaflet-in-r-map-as-png-or-jpg-file

NOTES:
* This should be done as a separate R script (perhaps run as part of the daily update!)
* The resulting images should be linked-to from the app 
* If someone wants a zoomed screen shot they'll need to screen capture their interactive session

**Comment by josefigueroa168** [comment]
Done
