### ISSUE TITLE
what is the best way to relate the factors we are measuring to the spread of disease?

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVIDMINDER#18]

**Comment by olyerickson** [comment]
Maybe this will help: https://ccforum.biomedcentral.com/articles/10.1186/s13054-020-2833-7

**Comment by olyerickson** [comment]
Esp this: https://ccforum.biomedcentral.com/articles/10.1186/s13054-020-2833-7/tables/1

**Comment by olyerickson** [comment]
I think our next proto plot should be nationwide hypertension rates: https://stateofchildhoodobesity.org/hypertension/

**Comment by josefigueroa168** [comment]
Social determinants team is working on this.
