### ISSUE TITLE
Add "target" selector to certain DI maps

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/COVIDMINDER#202]
Enable user to select between rates to compare to, e.g. on Hospital Beds or Testing Rates tabs. 

* Should be a few radio buttons, not a slider
* Should be labelled with value and association (e.g. country, like "South Korea")
* Certain text in LH column will need to become dynamic (like MORTALITYMINDER)

**Comment by josefigueroa168** [comment]
This was done for testing rates
