### ISSUE TITLE
Spiff up race plot: improve y axis, x-axis,  and remove white space

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVIDMINDER#225]
* order races alphabetically with Asian at the top
* Increase font size of races and ethnicities to make them pop in the document 
*Change limits on x-axis to be  smaller so there is less white space
*Label x axis Disparity Index

**Comment by olyerickson** [comment]
Corrected order and fonts

**Comment by olyerickson** [comment]
CLOSING
