### ISSUE TITLE
Link to actual page where data resides in NYState race plot

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVIDMINDER#226]

**Comment by bennek2** [comment]
in the data source link, make the link go directly to the page where we pick up. Then people can see rates and raw numbers easily.

**Comment by olyerickson** [comment]
Corrected citation below plot but didn't add as a link

**Comment by olyerickson** [comment]
NY COVIDTracker "Fatalities" page: https://on.ny.gov/2VehafT

**Comment by olyerickson** [comment]
DONE; Closing....
