### ISSUE TITLE
Spiff up Race Plot: improve -0.2 and 0.2 lines on plot

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVIDMINDER#227]
Problems and potential solutions.  Use your judgement if these fixes don't look
1) Lines are not consistent with color scheme and are not color blind friendly.
* Redraw in the red (0.2)  and the  blue (-0.2) that are the extremes of our existing color screen 
2) Not clear what lines mean.  upper and lower bounds don't mean anything to user  
* remove legend that defines line
* add text in the plot that explains.  Two ideas here
   option a) add text saying over-represented and text saying under-represented to right in either the top or middle of the plot
  option b) add text for per line.
3) Colors on the plot are not defined.  
* add legend that indicates what colors mean.

**Comment by olyerickson** [comment]
* Removed upper/lower bound legend
* Made the colors match our DI scheme
* DID NOT add overlay words (yet)
* DID NOT add legend for colors. Maybe do that ont he left?

**Comment by olyerickson** [comment]
* Added overlay words; simplified to "Higher" and "Lower"
* Legend for colors difficult, and ultimately not needed with overlay words. 
CLOSING for now; re-open if legend really needed.
