### ISSUE TITLE
NY Regional time series: One line per region

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/COVIDMINDER#260]
As per @bennek2 :

_Would be neat to see a plot of NY time with regions appearing as a single line.  i.e. you calculate the rate or number  for each region as a whole  and plot one line per region. This  would make it easier to see the differences between upstate and downstate._

**Comment by josefigueroa168** [comment]
Would this be *instead* of the individual counties or alongside them?

**Comment by josefigueroa168** [comment]
To be reviewed: https://github.com/TheRensselaerIDEA/COVIDMINDER/tree/issue-260

**Comment by josefigueroa168** [comment]
Done
