### ISSUE TITLE
Select different "Testing" baseline than South Korea

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/COVIDMINDER#262]
As per @bennek2 

* Use US baseline? 
* Use another country (e.g. germany)?

**Comment by olyerickson** [comment]
Maybe a drop-down selector?

**Comment by josefigueroa168** [comment]
Do we have this data (Other country rates?) Shouldn't be too troublesome, just importing the raw data to the app and normalizing it to the rate provided by the selector.
