### ISSUE TITLE
Switch regions used in NY regions to ones defined by DSRIP

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVIDMINDER#353]
https://www.health.ny.gov/health_care/medicaid/redesign/dsrip/performance_data/salient_performance_data.htm

This link contains the definitions and a map of the DSRIP regions.

The reason we are doing this is because the bRFSS data is in this format.

**Comment by bennek2** [comment]
Note that you will need to change the map used in the key as well.

**Comment by josefigueroa168** [comment]
Will look into this as well as how these regions correlate to economic re-open regions

**Comment by josefigueroa168** [comment]
Done
