### ISSUE TITLE
Make figure titles more self-explanatory and/or add subtitles

### ISSUE THREAD

**Issue by olyerickson** [TheRensselaerIDEA/COVIDMINDER#397]
Esp. in https://covidminder.idea.rpi.edu/?tab=national_report_card 

Examples: 

* US COVID-19 14-Day Case disparities compared to US Average
-- This plot is intended to highlight disparities in the rates of change, ie which states are getting more cases faster

* US COVID-19 14-Day Mortality disparities compared to US Average
-- This plot is also intended to highlight disparities in the rates of change, ie which states are getting more deaths faster

**Comment by josefigueroa168** [comment]
Each title is now a short name, with a question-driven explanatory subtitle. The 14-day plots are now 1-day plots.
